# Site settings
title: Crux Design Studio
email: team@crux.design
description: >
  More than just a creative team, Crux commits itself to helping people, brands, and companies solve problems through design.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.crux.design" # the base hostname & protocol for your site
twitter_username: crux_design
github_username:  cruxdesign
permalink: pretty

# Build settings
markdown: kramdown

#Collections
collections:
    works:
        output: true
        permalink: /works/:path/

